/* automatically generated by rust-bindgen 0.59.1 */

extern "C" {
    #[link_name = "\u{1}_Z18CalculatePerimeteriii"]
    pub fn CalculatePerimeter(
        side_1: ::std::os::raw::c_int,
        side_2: ::std::os::raw::c_int,
        side_3: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_Z12CalculateSumii"]
    pub fn CalculateSum(
        first_operand: ::std::os::raw::c_int,
        second_operand: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
